language: php

php:
  - 5.5
  - 5.6

sudo: false

before_install:
  - pip install --user codecov

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.0"
  - composer install

before_script:
  - chmod -R a+w runtime
  - mysql -e 'create database bootstrap_yii2_tests;'
  - php yii create-local-config/init
  - composer test-prepare
  - composer test-build

script:
  - cd tests && ../vendor/bin/codecept run unit,functional --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/codeception/_output/coverage.xml

after_success:
  - codecov
